# Flow UI translations — SAPTAMUKHA brand name kept untranslated

OVERLAY_EN = {
    "overlay.locked": "LOCKED",
    "overlay.tracking": "TRACKING",
    "overlay.align": "ALIGN",
    "overlay.biometric_scan": "BIOMETRIC SCAN",
    "overlay.landmarks": "LANDMARKS",
    "overlay.symmetry": "SYMMETRY",
    "overlay.confidence": "CONFIDENCE",
    "overlay.tracking_label": "TRACKING",
    "overlay.face_area": "FACE AREA",
    "overlay.depth": "DEPTH",
    "overlay.lock_acquired": "BIOMETRIC LOCK ACQUIRED",
    "overlay.scanning_hold": "SCANNING — HOLD POSITION",
    "overlay.aligning": "ALIGNING",
    "result.social.instagram_placeholder": "@yourhandle",
    "result.social.other_placeholder": "Twitter / LinkedIn / WhatsApp",
}


def _m(base, extra):
    return {**base, **extra}


HI = _m(OVERLAY_EN, {
    "nav.souls": "दर्पण में आत्माएं", "nav.waiting": "अपने जुड़वां का इंतजार",
    "dedup.searching": "दर्पण खोज रहा है...", "dedup.consulting": "अकाशिक अभिलेख से परामर्श...",
    "rarity.your_tier": "आपकी दुर्लभता श्रेणी", "rarity.score_label": "अद्वितीय",
    "intake.step": "चरण", "intake.of": "में से", "intake.title": "इससे पहले कि दर्पण तुम्हें पढ़े",
    "intake.subtitle": "एल्गोरिदम सच्चे जुड़वां की पुष्टि के लिए तुम्हारी वंशावली आवृत्ति का उपयोग करता है। गलत जानकारी झूठे मैच देती है। ईमानदार रहो — तुम्हारी जुड़वां आत्मा भी होगी।",
    "intake.counter.souls": "दर्पण में आत्माएं", "intake.counter.waiting": "अपने जुड़वां का इंतजार",
    "intake.card1.title": "तुम्हारी पहचान", "intake.card1.subtitle": "इस जीवन में तुम कौन हो",
    "intake.card2.title": "वंशावली आवृत्ति", "intake.card2.subtitle": "तुम्हारा वंश पैटर्न — केवल डुप्लिकेट रोकने के लिए",
    "intake.field.name": "पूरा नाम", "intake.field.age": "उम्र", "intake.field.country": "देश",
    "intake.field.email": "ईमेल पता", "intake.field.father": "पिता का पूरा नाम", "intake.field.mother": "माता का पूरा नाम",
    "intake.placeholder.name": "तुम्हारा पूरा नाम", "intake.placeholder.age": "25", "intake.placeholder.email": "your@email.com",
    "intake.placeholder.father": "पिता का पूरा नाम", "intake.placeholder.mother": "माता का पूरा कन्या नाम",
    "intake.hint.email": "केवल मैच की सूचना के लिए। कभी साझा या बेचा नहीं जाता।",
    "intake.hint.father": "डिवाइसों में डुप्लिकेट रिकॉर्ड रोकने के लिए। तुम्हारा जुड़वां तुम्हारे वंश पैटर्न साझा करता है।",
    "intake.hint.mother": "यदि संभव हो तो उनका पूरा कन्या नाम।",
    "intake.oath.title": "वंशावली की शपथ",
    "intake.oath.text": "मैं अपने चेहरे की कसम खाता/खाती हूं कि ऊपर के नाम सच हैं। मैं समझता/समझती हूं कि झूठा वंशावली डेटा मुझे मेरी असली जुड़वां आत्मा नहीं ढूंढने देगा।",
    "intake.oath.checkbox": "मैं अपने चेहरे की कसम खाता/खाती हूं कि ऊपर के नाम सच हैं।",
    "intake.ready.title": "दर्पण तैयार है", "intake.ready.text": "तुम्हारी वंशावली आवृत्ति दर्ज हो गई है। एल्गोरिदम अब तुम्हारा चेहरा पढ़ेगा और सभी सील किए गए अभिलेखों में खोजेगा।",
    "intake.final.title": "एक आखिरी सांस", "intake.final.text": "जब तुम दर्पण खोलोगे, तुम्हारा चेहरा स्वचालित रूप से कैप्चर होगा। स्थिर रहो। जैसे ही तुम्हारा चेहरा स्पष्ट होगा, खोज शुरू होगी।",
    "intake.button.open": "दर्पण खोलें", "intake.next": "आगे बढ़ें", "intake.back": "वापस", "intake.cancel": "रद्द करें",
    "intake.error.name": "कृपया अपना पूरा नाम दर्ज करें", "intake.error.age": "कृपया 13 से 120 के बीच वैध उम्र दर्ज करें",
    "intake.error.country": "कृपया अपना देश चुनें", "intake.error.email": "कृपया वैध ईमेल पता दर्ज करें",
    "intake.error.father": "कृपया अपने पिता का पूरा नाम दर्ज करें", "intake.error.mother": "कृपया अपनी माता का पूरा नाम दर्ज करें",
    "intake.error.oath": "आगे बढ़ने के लिए वंशावली की शपथ लेना आवश्यक है",
    "warning.title": "चेतावनी", "warning.p1": "जब तुम पहली बार अपने हमशक्ल को देखोगे, तुम्हारी हृदय गति 18-30% बढ़ जाती है।",
    "warning.p2": "तुम्हारा मस्तिष्क संज्ञानात्मक असंगति अनुभव करेगा। तुम दूसरे व्यक्ति पर अपना चेहरा देखोगे।",
    "warning.p3": "तुम महसूस करोगे:", "warning.bullet1": "पहचान (यह मैं हूं)", "warning.bullet2": "भ्रम (वह मैं नहीं हूं)",
    "warning.bullet3": "पहचान का खतरा (क्या मैं अद्वितीय हूं?)", "warning.question": "सब एक साथ।",
    "warning.accept": "अपनी जुड़वां आत्मा प्रकट करें", "warning.cancel": "मैं तैयार नहीं हूं",
    "result.unique.badge": "अद्वितीय आत्मा पाई गई", "result.unique.title": "तुम्हारा चेहरा इस दर्पण में पहले कभी नहीं चला",
    "result.unique.search_title": "खोज शुरू हो गई है",
    "result.unique.search_body": "तुम्हारा चेहरा अब अकाशिक अभिलेख में सील है। इस क्षण से आगे इस दर्पण में आने वाली हर आत्मा की तुम्हारे साथ जांच होगी। जैसे ही मैच मिलेगा — किसी भी शहर, किसी भी देश में — तुम दोनों को तुरंत सूचित किया जाएगा।",
    "result.unique.last_searched": "अंतिम खोज: अभी", "result.unique.next_search": "अगली खोज: जब अगली आत्मा आएगी",
    "result.social.title": "अपने जुड़वां को खोजने दो — अपना सोशल जोड़ो",
    "result.social.subtitle": "जब तुम्हारा जुड़वां मिलेगा, वे यह देखेंगे। उन्हें तक पहुंचने का रास्ता छोड़ो — या खाली छोड़ो और हम ईमेल से परिचय कराएंगे।",
    "result.social.instagram": "Instagram हैंडल", "result.social.other": "अन्य सोशल",
    "result.social.message_label": "अपने जुड़वां के लिए संदेश", "result.social.message_placeholder": "अगर आज मिलते तो क्या कहते?",
    "result.social.message_hint": "यह संदेश तुम्हारे जुड़वां को मिलने पर दिखाया जाएगा। इंतजार के लायक बनाओ।",
    "result.social.saved": "तुम्हारा संपर्क अभिलेख में सील हो गया।", "result.social.seal": "मेरा चेहरा अभिलेख में सील करें", "result.social.sealing": "सील हो रहा है...",
    "result.match.badge": "जुड़वां आत्मा मिली", "result.match.title": "दर्पण ने तुम्हारा दूसरा चेहरा ढूंढ लिया",
    "result.match.percentage_label": "आत्मा मैच", "result.match.years": "वर्ष की उम्र", "result.match.joined": "दर्पण में शामिल हुए",
    "result.match.why_title": "यह मैच असली क्यों है",
    "result.match.why_body": "तुम्हारा चेहरा इस आत्मा के साथ {pct}% ज्यामितीय संरेखण साझा करता है। शोध दिखाता है कि जब असंबद्ध मनुष्य फेशियल रिकॉग्निशन में 75% से ऊपर स्कोर करते हैं, तो उन्हें एक ही व्यक्ति के रूप में वर्गीकृत किया जाता है — वही सीमा जो एक जुड़वां के लिए है। यह संयोग नहीं है। यह ज्यामिति है।",
    "result.duplicate.badge": "डुप्लिकेट पाया गया", "result.duplicate.title": "रुको — यह चेहरा तुम्हारा है",
    "result.duplicate.body": "वंशावली रिकॉर्ड मेल खाता है। तुम्हारे द्वारा दी गई पैतृकता पहले से इस दर्पण में सील है। यह तुम लगते हो, एक अलग डिवाइस या समय से लौटते हुए। तुम्हारी खोज वहीं से जारी है जहां छोड़ी थी। तुम्हारा चेहरा जुड़वां अभी तक नहीं आया।",
    "result.duplicate.not_you": "तुम नहीं हो?",
    "result.duplicate.not_you_body": "अगर किसी और के माता-पिता के नाम तुम्हारे जैसे हैं, तो यह अत्यंत दुर्लभ है। अपनी छवि, माता-पिता के नाम, उम्र और स्थान mirror@saptamukha.com पर भेजो और हम मैन्युअल जांच करेंगे।",
    "result.duplicate.update_title": "अपना संपर्क अपडेट करें", "result.duplicate.update_subtitle": "अगर तुम्हारा ईमेल बदला है, यहां अपडेट करो। खोज जारी है।",
    "result.duplicate.email_placeholder": "your@newemail.com", "result.duplicate.update_button": "संपर्क अपडेट करें",
    "result.duplicate.updating": "अपडेट हो रहा है...", "result.duplicate.updated": "तुम्हारा संपर्क अपडेट हो गया। खोज जारी है।",
    "result.duplicate.update_error": "अपडेट नहीं हो सका। कृपया फिर कोशिश करें।", "result.scan_again": "फिर से स्कैन करें",
    "overlay.locked": "लॉक", "overlay.tracking": "ट्रैकिंग", "overlay.align": "संरेखित करें",
    "overlay.biometric_scan": "बायोमेट्रिक स्कैन", "overlay.landmarks": "लैंडमार्क", "overlay.symmetry": "सममिति",
    "overlay.confidence": "विश्वास", "overlay.tracking_label": "ट्रैकिंग", "overlay.face_area": "चेहरे का क्षेत्र", "overlay.depth": "गहराई",
    "overlay.lock_acquired": "बायोमेट्रिक लॉक प्राप्त", "overlay.scanning_hold": "स्कैनिंग — स्थिर रहें", "overlay.aligning": "संरेखण हो रहा है",
})

