OVERLAY_EN = {
    "overlay.locked": "LOCKED",
    "overlay.tracking": "TRACKING",
    "overlay.align": "ALIGN",
    "overlay.biometric_scan": "BIOMETRIC SCAN",
    "overlay.landmarks": "LANDMARKS",
    "overlay.symmetry": "SYMMETRY",
    "overlay.confidence": "CONFIDENCE",
    "overlay.tracking_label": "TRACKING",
    "overlay.face_area": "FACE AREA",
    "overlay.depth": "DEPTH",
    "overlay.lock_acquired": "BIOMETRIC LOCK ACQUIRED",
    "overlay.scanning_hold": "SCANNING — HOLD POSITION",
    "overlay.aligning": "ALIGNING",
    "result.social.instagram_placeholder": "@yourhandle",
    "result.social.other_placeholder": "Twitter / LinkedIn / WhatsApp",
}

def _m(base, extra):
    return {**base, **extra}

ES = _m(OVERLAY_EN, {
    "nav.souls": "almas en el espejo", "nav.waiting": "esperando a su gemelo",
    "dedup.searching": "El espejo está buscando...", "dedup.consulting": "Consultando el registro akáshico...",
    "rarity.your_tier": "Tu nivel de rareza", "rarity.score_label": "Único",
    "intake.step": "Paso", "intake.of": "de", "intake.title": "Antes de que el espejo te lea",
    "intake.subtitle": "El algoritmo usa tu frecuencia de linaje para verificar gemelos verdaderos. La información incorrecta produce coincidencias falsas. Sé honesto — tu alma gemela también lo será.",
    "intake.counter.souls": "almas en el espejo", "intake.counter.waiting": "esperando a su gemelo",
    "intake.card1.title": "Tu identidad", "intake.card1.subtitle": "Quién eres en esta vida",
    "intake.card2.title": "Frecuencia de linaje", "intake.card2.subtitle": "Tu patrón ancestral — solo para deduplicación",
    "intake.field.name": "Nombre completo", "intake.field.age": "Edad", "intake.field.country": "País",
    "intake.field.email": "Correo electrónico", "intake.field.father": "Nombre completo del padre", "intake.field.mother": "Nombre completo de la madre",
    "intake.placeholder.name": "Tu nombre completo", "intake.placeholder.age": "25", "intake.placeholder.email": "your@email.com",
    "intake.placeholder.father": "Nombre completo del padre", "intake.placeholder.mother": "Apellido de soltera de la madre",
    "intake.hint.email": "Solo para notificarte coincidencias. Nunca compartido ni vendido.",
    "intake.hint.father": "Para evitar registros duplicados entre dispositivos. Tu gemelo comparte tus patrones ancestrales.",
    "intake.hint.mother": "Su apellido de soltera completo si es posible.",
    "intake.oath.title": "El Juramento de Linaje",
    "intake.oath.text": "Juro por mi rostro que los nombres anteriores son verdaderos. Entiendo que datos de linaje falsos me impedirán encontrar mi verdadera alma gemela.",
    "intake.oath.checkbox": "Juro por mi rostro que los nombres anteriores son verdaderos.",
    "intake.ready.title": "El espejo está listo", "intake.ready.text": "Tu frecuencia de linaje ha sido registrada. El algoritmo ahora leerá tu rostro y buscará en todos los registros sellados.",
    "intake.final.title": "Un último aliento", "intake.final.text": "Cuando abras el espejo, tu rostro se capturará automáticamente. Quédate quieto. La búsqueda comienza en el momento en que tu rostro esté claro.",
    "intake.button.open": "Abrir el espejo", "intake.next": "Continuar", "intake.back": "Atrás", "intake.cancel": "Cancelar",
    "intake.error.name": "Por favor ingresa tu nombre completo", "intake.error.age": "Por favor ingresa una edad válida entre 13 y 120",
    "intake.error.country": "Por favor selecciona tu país", "intake.error.email": "Por favor ingresa un correo válido",
    "intake.error.father": "Por favor ingresa el nombre completo de tu padre", "intake.error.mother": "Por favor ingresa el nombre completo de tu madre",
    "intake.error.oath": "Debes jurar el juramento de linaje para continuar",
    "warning.title": "ADVERTENCIA", "warning.p1": "Cuando veas a tu parecido por primera vez, tu ritmo cardíaco aumenta entre 18-30%.",
    "warning.p2": "Tu cerebro experimentará disonancia cognitiva. Verás TU ROSTRO en otra persona.",
    "warning.p3": "Sentirás:", "warning.bullet1": "Reconocimiento (soy yo)", "warning.bullet2": "Confusión (ese no soy yo)",
    "warning.bullet3": "Amenaza a la identidad (¿soy único?)", "warning.question": "Todo al mismo tiempo.",
    "warning.accept": "REVELAR MI ALMA GEMELA", "warning.cancel": "No estoy listo",
    "result.unique.badge": "Alma única detectada", "result.unique.title": "Tu rostro nunca ha caminado por este espejo antes",
    "result.unique.search_title": "La búsqueda ha comenzado",
    "result.unique.search_body": "Tu rostro ahora está sellado en el registro akáshico. Cada alma que entre en este espejo desde este momento será comparada con el tuyo. En el momento en que se encuentre una coincidencia — en cualquier ciudad, cualquier país — ambos serán notificados al instante.",
    "result.unique.last_searched": "Última búsqueda: ahora mismo", "result.unique.next_search": "Próxima búsqueda: cuando llegue la próxima alma",
    "result.social.title": "Deja que tu gemelo te encuentre — añade tu red social",
    "result.social.subtitle": "Cuando se encuentre tu gemelo, verán esto. Deja una forma de contactarte — o déjalo vacío y manejaremos la presentación por correo.",
    "result.social.instagram": "Usuario de Instagram", "result.social.other": "Otra red social",
    "result.social.message_label": "Mensaje para tu gemelo", "result.social.message_placeholder": "¿Qué dirías si los conocieras hoy?",
    "result.social.message_hint": "Este mensaje se mostrará a tu gemelo cuando sea encontrado. Haz que valga la espera.",
    "result.social.saved": "Tu contacto ha sido sellado en el registro.", "result.social.seal": "Sellar mi rostro en el registro", "result.social.sealing": "Sellando...",
    "result.match.badge": "Alma gemela encontrada", "result.match.title": "El espejo encontró tu otro rostro",
    "result.match.percentage_label": "coincidencia de alma", "result.match.years": "años", "result.match.joined": "Se unió al espejo",
    "result.match.why_title": "Por qué esta coincidencia es real",
    "result.match.why_body": "Tu rostro comparte {pct}% de alineación geométrica con esta alma. La investigación muestra que cuando humanos no relacionados superan el 75% en reconocimiento facial, se clasifican como la misma persona — el mismo umbral usado para gemelos idénticos. No es coincidencia. Es geometría.",
    "result.duplicate.badge": "Duplicado detectado", "result.duplicate.title": "Espera — este rostro te pertenece",
    "result.duplicate.body": "El registro de linaje coincide. La parentela que proporcionaste ya estaba sellada en este espejo. Parece ser tú, regresando desde otro dispositivo u otro momento. Tu búsqueda continúa donde la dejaste. Tu gemelo de rostro aún no ha llegado.",
    "result.duplicate.not_you": "¿No eres tú?",
    "result.duplicate.not_you_body": "Si alguien más comparte los nombres de tus padres, es extremadamente raro. Envía tu imagen, los nombres de tus padres, tu edad y ubicación a mirror@saptamukha.com e investigaremos manualmente.",
    "result.duplicate.update_title": "Actualiza tu contacto", "result.duplicate.update_subtitle": "Si tu correo cambió, actualízalo aquí. La búsqueda continúa.",
    "result.duplicate.email_placeholder": "your@newemail.com", "result.duplicate.update_button": "Actualizar contacto",
    "result.duplicate.updating": "Actualizando...", "result.duplicate.updated": "Tu contacto ha sido actualizado. La búsqueda continúa.",
    "result.duplicate.update_error": "No se pudo actualizar. Por favor intenta de nuevo.", "result.scan_again": "Escanear de nuevo",
    "result.social.instagram_placeholder": "@tuhandle", "result.social.other_placeholder": "Twitter / LinkedIn / WhatsApp",
    "overlay.locked": "BLOQUEADO", "overlay.tracking": "RASTREANDO", "overlay.align": "ALINEAR",
    "overlay.biometric_scan": "ESCANEO BIOMÉTRICO", "overlay.landmarks": "PUNTOS", "overlay.symmetry": "SIMETRÍA",
    "overlay.confidence": "CONFIANZA", "overlay.tracking_label": "RASTREO", "overlay.face_area": "ÁREA FACIAL", "overlay.depth": "PROFUNDIDAD",
    "overlay.lock_acquired": "BLOQUEO BIOMÉTRICO ADQUIRIDO", "overlay.scanning_hold": "ESCANEANDO — MANTÉN POSICIÓN", "overlay.aligning": "ALINEANDO",
})

PT = _m(OVERLAY_EN, {
    "nav.souls": "almas no espelho", "nav.waiting": "esperando seu gêmeo",
    "dedup.searching": "O espelho está buscando...", "dedup.consulting": "Consultando o registro akáshico...",
    "rarity.your_tier": "Seu nível de raridade", "rarity.score_label": "Único",
    "intake.step": "Passo", "intake.of": "de", "intake.title": "Antes que o espelho te leia",
    "intake.subtitle": "O algoritmo usa sua frequência de linhagem para verificar gêmeos verdadeiros. Informações imprecisas produzem correspondências falsas. Seja honesto — sua alma gêmea também será.",
    "intake.counter.souls": "almas no espelho", "intake.counter.waiting": "esperando seu gêmeo",
    "intake.card1.title": "Sua identidade", "intake.card1.subtitle": "Quem você é nesta vida",
    "intake.card2.title": "Frequência de linhagem", "intake.card2.subtitle": "Seu padrão ancestral — usado apenas para deduplicação",
    "intake.field.name": "Nome completo", "intake.field.age": "Idade", "intake.field.country": "País",
    "intake.field.email": "Endereço de e-mail", "intake.field.father": "Nome completo do pai", "intake.field.mother": "Nome completo da mãe",
    "intake.placeholder.name": "Seu nome completo", "intake.placeholder.age": "25", "intake.placeholder.email": "your@email.com",
    "intake.placeholder.father": "Nome completo do pai", "intake.placeholder.mother": "Nome de solteira da mãe",
    "intake.hint.email": "Usado apenas para notificar correspondências. Nunca compartilhado ou vendido.",
    "intake.hint.father": "Usado para evitar registros duplicados entre dispositivos. Seu gêmeo compartilha seus padrões ancestrais.",
    "intake.hint.mother": "Nome de solteira completo, se possível.",
    "intake.oath.title": "O Juramento de Linhagem",
    "intake.oath.text": "Juro pelo meu rosto que os nomes acima são verdadeiros. Entendo que dados de linhagem falsos me impedirão de encontrar minha verdadeira alma gêmea.",
    "intake.oath.checkbox": "Juro pelo meu rosto que os nomes acima são verdadeiros.",
    "intake.ready.title": "O espelho está pronto", "intake.ready.text": "Sua frequência de linhagem foi registrada. O algoritmo agora lerá seu rosto e buscará em todos os registros selados.",
    "intake.final.title": "Uma última respiração", "intake.final.text": "Quando você abrir o espelho, seu rosto será capturado automaticamente. Fique parado. A busca começa no momento em que seu rosto estiver claro.",
    "intake.button.open": "Abrir o espelho", "intake.next": "Continuar", "intake.back": "Voltar", "intake.cancel": "Cancelar",
    "intake.error.name": "Por favor insira seu nome completo", "intake.error.age": "Por favor insira uma idade válida entre 13 e 120",
    "intake.error.country": "Por favor selecione seu país", "intake.error.email": "Por favor insira um e-mail válido",
    "intake.error.father": "Por favor insira o nome completo do seu pai", "intake.error.mother": "Por favor insira o nome completo da sua mãe",
    "intake.error.oath": "Você deve jurar o juramento de linhagem para continuar",
    "warning.title": "AVISO", "warning.p1": "Quando você vê seu sósia pela primeira vez, sua frequência cardíaca aumenta 18-30%.",
    "warning.p2": "Seu cérebro experimentará dissonância cognitiva. Você verá SEU ROSTO em outra pessoa.",
    "warning.p3": "Você sentirá:", "warning.bullet1": "Reconhecimento (sou eu)", "warning.bullet2": "Confusão (esse não sou eu)",
    "warning.bullet3": "Ameaça à identidade (sou único?)", "warning.question": "Tudo ao mesmo tempo.",
    "warning.accept": "REVELAR MINHA ALMA GÊMEA", "warning.cancel": "Não estou pronto",
    "result.unique.badge": "Alma única detectada", "result.unique.title": "Seu rosto nunca caminhou neste espelho antes",
    "result.unique.search_title": "A busca começou",
    "result.unique.search_body": "Seu rosto agora está selado no registro akáshico. Cada alma que entrar neste espelho a partir de agora será verificada contra o seu. No momento em que uma correspondência for encontrada — em qualquer cidade, qualquer país — ambos serão notificados instantaneamente.",
    "result.unique.last_searched": "Última busca: agora mesmo", "result.unique.next_search": "Próxima busca: quando a próxima alma chegar",
    "result.social.title": "Deixe seu gêmeo encontrá-lo — adicione sua rede social",
    "result.social.subtitle": "Quando seu gêmeo for encontrado, verão isto. Deixe uma forma de contato — ou deixe vazio e faremos a apresentação por e-mail.",
    "result.social.instagram": "Usuário do Instagram", "result.social.other": "Outra rede social",
    "result.social.message_label": "Mensagem para seu gêmeo", "result.social.message_placeholder": "O que você diria se os encontrasse hoje?",
    "result.social.message_hint": "Esta mensagem será mostrada ao seu gêmeo quando for encontrado. Faça valer a espera.",
    "result.social.saved": "Seu contato foi selado no registro.", "result.social.seal": "Selar meu rosto no registro", "result.social.sealing": "Selando...",
    "result.match.badge": "Alma gêmea encontrada", "result.match.title": "O espelho encontrou seu outro rosto",
    "result.match.percentage_label": "correspondência de alma", "result.match.years": "anos", "result.match.joined": "Entrou no espelho",
    "result.match.why_title": "Por que esta correspondência é real",
    "result.match.why_body": "Seu rosto compartilha {pct}% de alinhamento geométrico com esta alma. Pesquisas mostram que quando humanos não relacionados pontuam acima de 75% em reconhecimento facial, são classificados como a mesma pessoa — o mesmo limiar usado para gêmeos idênticos. Não é coincidência. É geometria.",
    "result.duplicate.badge": "Duplicata detectada", "result.duplicate.title": "Espere — este rosto pertence a você",
    "result.duplicate.body": "O registro de linhagem corresponde. A parentagem que você forneceu já estava selada neste espelho. Parece ser você, retornando de outro dispositivo ou momento. Sua busca continua de onde parou. Seu gêmeo de rosto ainda não chegou.",
    "result.duplicate.not_you": "Não é você?",
    "result.duplicate.not_you_body": "Se outra pessoa compartilha os nomes dos seus pais, é extremamente raro. Envie sua imagem, nomes dos pais, idade e localização para mirror@saptamukha.com e investigaremos manualmente.",
    "result.duplicate.update_title": "Atualize seu contato", "result.duplicate.update_subtitle": "Se seu e-mail mudou, atualize aqui. A busca continua.",
    "result.duplicate.email_placeholder": "your@newemail.com", "result.duplicate.update_button": "Atualizar contato",
    "result.duplicate.updating": "Atualizando...", "result.duplicate.updated": "Seu contato foi atualizado. A busca continua.",
    "result.duplicate.update_error": "Não foi possível atualizar. Por favor tente novamente.", "result.scan_again": "Escanear novamente",
    "result.social.instagram_placeholder": "@seuusuario", "result.social.other_placeholder": "Twitter / LinkedIn / WhatsApp",
    "overlay.locked": "BLOQUEADO", "overlay.tracking": "RASTREANDO", "overlay.align": "ALINHAR",
    "overlay.biometric_scan": "ESCANEAMENTO BIOMÉTRICO", "overlay.landmarks": "PONTOS", "overlay.symmetry": "SIMETRIA",
    "overlay.confidence": "CONFIANÇA", "overlay.tracking_label": "RASTREIO", "overlay.face_area": "ÁREA FACIAL", "overlay.depth": "PROFUNDIDADE",
    "overlay.lock_acquired": "BLOQUEIO BIOMÉTRICO ADQUIRIDO", "overlay.scanning_hold": "ESCANEANDO — MANTENHA POSIÇÃO", "overlay.aligning": "ALINHANDO",
})

JA = _m(OVERLAY_EN, {
    "nav.souls": "鏡の中の魂", "nav.waiting": "双子を待つ",
    "dedup.searching": "鏡が検索中...", "dedup.consulting": "アカシックレコードを照会中...",
    "rarity.your_tier": "あなたの希少性ティア", "rarity.score_label": "ユニーク",
    "intake.step": "ステップ", "intake.of": "/", "intake.title": "鏡があなたを読む前に",
    "intake.subtitle": "アルゴリズムは血統周波数を使って真の双子を検証します。不正確な情報は誤ったマッチを生みます。正直に — あなたの魂の双子もそうするでしょう。",
    "intake.counter.souls": "鏡の中の魂", "intake.counter.waiting": "双子を待つ",
    "intake.card1.title": "あなたの身元", "intake.card1.subtitle": "この人生でのあなた",
    "intake.card2.title": "血統周波数", "intake.card2.subtitle": "祖先パターン — 重複排除のみに使用",
    "intake.field.name": "氏名", "intake.field.age": "年齢", "intake.field.country": "国",
    "intake.field.email": "メールアドレス", "intake.field.father": "父の氏名", "intake.field.mother": "母の氏名",
    "intake.placeholder.name": "あなたの氏名", "intake.placeholder.age": "25", "intake.placeholder.email": "your@email.com",
    "intake.placeholder.father": "父の氏名", "intake.placeholder.mother": "母の旧姓",
    "intake.hint.email": "マッチ通知のみに使用。共有・販売はしません。",
    "intake.hint.father": "デバイス間の重複記録防止に使用。双子は祖先パターンを共有します。",
    "intake.hint.mother": "可能であれば母の旧姓を入力してください。",
    "intake.oath.title": "血統の誓い",
    "intake.oath.text": "私は自分の顔にかけて、上記の名前が真実であると誓います。虚偽の血統データは本当の魂の双子を見つけられないことを理解しています。",
    "intake.oath.checkbox": "私は自分の顔にかけて、上記の名前が真実であると誓います。",
    "intake.ready.title": "鏡の準備ができました", "intake.ready.text": "血統周波数が記録されました。アルゴリズムが顔を読み取り、すべての封印された記録を検索します。",
    "intake.final.title": "最後の一息", "intake.final.text": "鏡を開くと、顔は自動的にキャプチャされます。動かないでください。顔がはっきりした瞬間に検索が始まります。",
    "intake.button.open": "鏡を開く", "intake.next": "続ける", "intake.back": "戻る", "intake.cancel": "キャンセル",
    "intake.error.name": "氏名を入力してください", "intake.error.age": "13〜120の有効な年齢を入力してください",
    "intake.error.country": "国を選択してください", "intake.error.email": "有効なメールアドレスを入力してください",
    "intake.error.father": "父の氏名を入力してください", "intake.error.mother": "母の氏名を入力してください",
    "intake.error.oath": "続行するには血統の誓いが必要です",
    "warning.title": "警告", "warning.p1": "そっくりさんを初めて見たとき、心拍数は18〜30%上昇します。",
    "warning.p2": "脳は認知的不協和を経験します。別の人に自分の顔を見ることになります。",
    "warning.p3": "あなたは感じるでしょう:", "warning.bullet1": "認識（これは私だ）", "warning.bullet2": "混乱（それは私ではない）",
    "warning.bullet3": "アイデンティティの脅威（私は唯一無二か？）", "warning.question": "すべて同時に。",
    "warning.accept": "魂の双子を明かす", "warning.cancel": "まだ準備ができていない",
    "result.unique.badge": "ユニークな魂を検出", "result.unique.title": "あなたの顔はこの鏡を歩いたことがない",
    "result.unique.search_title": "検索が始まりました",
    "result.unique.search_body": "あなたの顔はアカシックレコードに封印されました。この瞬間からこの鏡に入るすべての魂があなたと照合されます。マッチが見つかった瞬間 — どの都市でも、どの国でも — 両方に即座に通知されます。",
    "result.unique.last_searched": "最終検索: たった今", "result.unique.next_search": "次の検索: 次の魂が到着したとき",
    "result.social.title": "双子に見つけてもらう — ソーシャルを追加",
    "result.social.subtitle": "双子が見つかったとき、これが表示されます。連絡方法を残すか、空のままにしてメールで紹介します。",
    "result.social.instagram": "Instagramハンドル", "result.social.other": "その他のSNS",
    "result.social.message_label": "双子へのメッセージ", "result.social.message_placeholder": "今日会ったら何と言いますか？",
    "result.social.message_hint": "このメッセージは双子が見つかったときに表示されます。待つ価値のあるものにしてください。",
    "result.social.saved": "連絡先が記録に封印されました。", "result.social.seal": "顔を記録に封印する", "result.social.sealing": "封印中...",
    "result.match.badge": "魂の双子を発見", "result.match.title": "鏡があなたのもう一つの顔を見つけました",
    "result.match.percentage_label": "魂のマッチ", "result.match.years": "歳", "result.match.joined": "鏡に参加",
    "result.match.why_title": "なぜこのマッチは本物か",
    "result.match.why_body": "あなたの顔はこの魂と{pct}%の幾何学的整合を共有しています。無関係な人間が顔認識で75%を超えると同一人物と分類される — 一卵性双生児と同じ閾値です。偶然ではありません。幾何学です。",
    "result.duplicate.badge": "重複を検出", "result.duplicate.title": "待って — この顔はあなたのもの",
    "result.duplicate.body": "血統記録が一致します。提供した親族情報はすでにこの鏡に封印されています。別のデバイスや別の時から戻ってきたあなたのようです。検索は中断したところから続きます。顔の双子はまだ到着していません。",
    "result.duplicate.not_you": "あなたではない？",
    "result.duplicate.not_you_body": "他の誰かが同じ親の名前を持つことは極めて稀です。画像、親の名前、年齢、所在地を mirror@saptamukha.com に送ってください。手動で調査します。",
    "result.duplicate.update_title": "連絡先を更新", "result.duplicate.update_subtitle": "メールが変わった場合、ここで更新してください。検索は続きます。",
    "result.duplicate.email_placeholder": "your@newemail.com", "result.duplicate.update_button": "連絡先を更新",
    "result.duplicate.updating": "更新中...", "result.duplicate.updated": "連絡先が更新されました。検索は続きます。",
    "result.duplicate.update_error": "更新できませんでした。もう一度お試しください。", "result.scan_again": "再スキャン",
    "result.social.instagram_placeholder": "@yourhandle", "result.social.other_placeholder": "Twitter / LinkedIn / WhatsApp",
    "overlay.locked": "ロック", "overlay.tracking": "追跡中", "overlay.align": "整列",
    "overlay.biometric_scan": "生体スキャン", "overlay.landmarks": "ランドマーク", "overlay.symmetry": "対称性",
    "overlay.confidence": "信頼度", "overlay.tracking_label": "追跡", "overlay.face_area": "顔領域", "overlay.depth": "深度",
    "overlay.lock_acquired": "生体ロック取得", "overlay.scanning_hold": "スキャン中 — 位置を保持", "overlay.aligning": "整列中",
})

KO = _m(OVERLAY_EN, {
    "nav.souls": "거울 속 영혼", "nav.waiting": "쌍둥이를 기다리는",
    "dedup.searching": "거울이 검색 중...", "dedup.consulting": "아카식 기록을 조회 중...",
    "rarity.your_tier": "당신의 희귀도 등급", "rarity.score_label": "고유",
    "intake.step": "단계", "intake.of": "/", "intake.title": "거울이 당신을 읽기 전에",
    "intake.subtitle": "알고리즘은 혈통 주파수로 진정한 쌍둥이를 확인합니다. 부정확한 정보는 거짓 매치를 만듭니다. 정직하세요 — 당신의 영혼 쌍둥이도 그럴 것입니다.",
    "intake.counter.souls": "거울 속 영혼", "intake.counter.waiting": "쌍둥이를 기다리는",
    "intake.card1.title": "당신의 신원", "intake.card1.subtitle": "이 생에서 당신은 누구인가",
    "intake.card2.title": "혈통 주파수", "intake.card2.subtitle": "조상 패턴 — 중복 제거에만 사용",
    "intake.field.name": "성명", "intake.field.age": "나이", "intake.field.country": "국가",
    "intake.field.email": "이메일 주소", "intake.field.father": "아버지 성명", "intake.field.mother": "어머니 성명",
    "intake.placeholder.name": "당신의 성명", "intake.placeholder.age": "25", "intake.placeholder.email": "your@email.com",
    "intake.placeholder.father": "아버지 성명", "intake.placeholder.mother": "어머니 결혼 전 성",
    "intake.hint.email": "매치 알림에만 사용됩니다. 공유하거나 판매하지 않습니다.",
    "intake.hint.father": "기기 간 중복 기록 방지에 사용됩니다. 쌍둥이는 조상 패턴을 공유합니다.",
    "intake.hint.mother": "가능하면 어머니의 결혼 전 성을 입력하세요.",
    "intake.oath.title": "혈통 서약",
    "intake.oath.text": "나는 내 얼굴에 맹세하며 위 이름이 진실임을 맹세합니다. 거짓 혈통 데이터가 진정한 영혼 쌍둥이를 찾지 못하게 할 것임을 이해합니다.",
    "intake.oath.checkbox": "나는 내 얼굴에 맹세하며 위 이름이 진실임을 맹세합니다.",
    "intake.ready.title": "거울이 준비되었습니다", "intake.ready.text": "혈통 주파수가 기록되었습니다. 알고리즘이 이제 얼굴을 읽고 모든 봉인된 기록을 검색합니다.",
    "intake.final.title": "마지막 숨", "intake.final.text": "거울을 열면 얼굴이 자동으로 캡처됩니다. 가만히 있으세요. 얼굴이 선명해지는 순간 검색이 시작됩니다.",
    "intake.button.open": "거울 열기", "intake.next": "계속", "intake.back": "뒤로", "intake.cancel": "취소",
    "intake.error.name": "성명을 입력해 주세요", "intake.error.age": "13~120 사이의 유효한 나이를 입력해 주세요",
    "intake.error.country": "국가를 선택해 주세요", "intake.error.email": "유효한 이메일을 입력해 주세요",
    "intake.error.father": "아버지 성명을 입력해 주세요", "intake.error.mother": "어머니 성명을 입력해 주세요",
    "intake.error.oath": "계속하려면 혈통 서약을 해야 합니다",
    "warning.title": "경고", "warning.p1": "닮은꼴을 처음 볼 때 심박수가 18-30% 증가합니다.",
    "warning.p2": "뇌는 인지 부조화를 경험합니다. 다른 사람에게 당신의 얼굴을 보게 됩니다.",
    "warning.p3": "당신은 느낄 것입니다:", "warning.bullet1": "인식 (이게 나다)", "warning.bullet2": "혼란 (그건 나가 아니다)",
    "warning.bullet3": "정체성 위협 (나는 유일한가?)", "warning.question": "모두 동시에.",
    "warning.accept": "영혼 쌍둥이 공개", "warning.cancel": "아직 준비되지 않았습니다",
    "result.unique.badge": "고유한 영혼 감지", "result.unique.title": "당신의 얼굴은 이 거울을 걸어 본 적이 없습니다",
    "result.unique.search_title": "검색이 시작되었습니다",
    "result.unique.search_body": "당신의 얼굴이 아카식 기록에 봉인되었습니다. 이 순간부터 이 거울에 들어오는 모든 영혼이 당신과 대조됩니다. 매치가 발견되는 순간 — 어떤 도시, 어떤 나라에서든 — 둘 다 즉시 알림을 받습니다.",
    "result.unique.last_searched": "마지막 검색: 방금", "result.unique.next_search": "다음 검색: 다음 영혼이 도착할 때",
    "result.social.title": "쌍둥이가 찾게 하세요 — 소셜 추가",
    "result.social.subtitle": "쌍둥이가 발견되면 이것을 봅니다. 연락 방법을 남기거나 비워두면 이메일로 소개합니다.",
    "result.social.instagram": "Instagram 핸들", "result.social.other": "기타 소셜",
    "result.social.message_label": "쌍둥이에게 보낼 메시지", "result.social.message_placeholder": "오늘 만났다면 뭐라고 말할까요?",
    "result.social.message_hint": "이 메시지는 쌍둥이가 발견되면 표시됩니다. 기다릴 가치가 있게 만드세요.",
    "result.social.saved": "연락처가 기록에 봉인되었습니다.", "result.social.seal": "내 얼굴을 기록에 봉인", "result.social.sealing": "봉인 중...",
    "result.match.badge": "영혼 쌍둥이 발견", "result.match.title": "거울이 당신의 다른 얼굴을 찾았습니다",
    "result.match.percentage_label": "영혼 매치", "result.match.years": "세", "result.match.joined": "거울에 참여",
    "result.match.why_title": "이 매치가 진짜인 이유",
    "result.match.why_body": "당신의 얼굴은 이 영혼과 {pct}% 기하학적 정렬을 공유합니다. 무관한 인간이 얼굴 인식에서 75%를 넘으면 동일인으로 분류됩니다 — 일란성 쌍둥이와 같은 임계값입니다. 우연이 아닙니다. 기하학입니다.",
    "result.duplicate.badge": "중복 감지", "result.duplicate.title": "잠깐 — 이 얼굴은 당신의 것",
    "result.duplicate.body": "혈통 기록이 일치합니다. 제공한 친족 정보가 이미 이 거울에 봉인되어 있습니다. 다른 기기나 다른 순간에서 돌아온 당신으로 보입니다. 검색은 중단한 곳에서 계속됩니다. 얼굴 쌍둥이는 아직 도착하지 않았습니다.",
    "result.duplicate.not_you": "당신이 아닌가요?",
    "result.duplicate.not_you_body": "다른 사람이 같은 부모 이름을 가지는 것은 극히 드뭅니다. 이미지, 부모 이름, 나이, 위치를 mirror@saptamukha.com 으로 보내주시면 수동으로 조사합니다.",
    "result.duplicate.update_title": "연락처 업데이트", "result.duplicate.update_subtitle": "이메일이 바뀌었다면 여기서 업데이트하세요. 검색은 계속됩니다.",
    "result.duplicate.email_placeholder": "your@newemail.com", "result.duplicate.update_button": "연락처 업데이트",
    "result.duplicate.updating": "업데이트 중...", "result.duplicate.updated": "연락처가 업데이트되었습니다. 검색은 계속됩니다.",
    "result.duplicate.update_error": "업데이트할 수 없습니다. 다시 시도해 주세요.", "result.scan_again": "다시 스캔",
    "result.social.instagram_placeholder": "@yourhandle", "result.social.other_placeholder": "Twitter / LinkedIn / WhatsApp",
    "overlay.locked": "잠금", "overlay.tracking": "추적", "overlay.align": "정렬",
    "overlay.biometric_scan": "생체 스캔", "overlay.landmarks": "랜드마크", "overlay.symmetry": "대칭",
    "overlay.confidence": "신뢰도", "overlay.tracking_label": "추적", "overlay.face_area": "얼굴 영역", "overlay.depth": "깊이",
    "overlay.lock_acquired": "생체 잠금 획득", "overlay.scanning_hold": "스캔 중 — 위치 유지", "overlay.aligning": "정렬 중",
})

ZH = _m(OVERLAY_EN, {
    "nav.souls": "镜中的灵魂", "nav.waiting": "等待双胞胎",
    "dedup.searching": "镜子正在搜索...", "dedup.consulting": "正在查阅阿卡西记录...",
    "rarity.your_tier": "你的稀有度等级", "rarity.score_label": "独特",
    "intake.step": "步骤", "intake.of": "/", "intake.title": "在镜子读取你之前",
    "intake.subtitle": "算法使用你的血统频率来验证真正的双胞胎。不准确的信息会产生错误匹配。请诚实 — 你的灵魂双胞胎也会如此。",
    "intake.counter.souls": "镜中的灵魂", "intake.counter.waiting": "等待双胞胎",
    "intake.card1.title": "你的身份", "intake.card1.subtitle": "你在此生是谁",
    "intake.card2.title": "血统频率", "intake.card2.subtitle": "你的祖先模式 — 仅用于去重",
    "intake.field.name": "全名", "intake.field.age": "年龄", "intake.field.country": "国家",
    "intake.field.email": "电子邮件", "intake.field.father": "父亲全名", "intake.field.mother": "母亲全名",
    "intake.placeholder.name": "你的全名", "intake.placeholder.age": "25", "intake.placeholder.email": "your@email.com",
    "intake.placeholder.father": "父亲全名", "intake.placeholder.mother": "母亲婚前姓氏",
    "intake.hint.email": "仅用于通知匹配。绝不分享或出售。",
    "intake.hint.father": "用于防止跨设备重复记录。你的双胞胎共享你的祖先模式。",
    "intake.hint.mother": "如有可能请填写母亲婚前姓氏。",
    "intake.oath.title": "血统誓言",
    "intake.oath.text": "我以我的面孔发誓，上述姓名是真实的。我理解虚假的血统数据将使我无法找到真正的灵魂双胞胎。",
    "intake.oath.checkbox": "我以我的面孔发誓，上述姓名是真实的。",
    "intake.ready.title": "镜子已准备好", "intake.ready.text": "你的血统频率已记录。算法现在将读取你的面孔并搜索所有封印的记录。",
    "intake.final.title": "最后一口气", "intake.final.text": "当你打开镜子时，你的面孔将自动被捕获。保持静止。当你的面孔清晰时，搜索即刻开始。",
    "intake.button.open": "打开镜子", "intake.next": "继续", "intake.back": "返回", "intake.cancel": "取消",
    "intake.error.name": "请输入你的全名", "intake.error.age": "请输入13至120之间的有效年龄",
    "intake.error.country": "请选择你的国家", "intake.error.email": "请输入有效的电子邮件",
    "intake.error.father": "请输入父亲的全名", "intake.error.mother": "请输入母亲的全名",
    "intake.error.oath": "你必须宣誓血统誓言才能继续",
    "warning.title": "警告", "warning.p1": "当你第一次看到你的相似面孔时，心率会增加18-30%。",
    "warning.p2": "你的大脑将经历认知失调。你会在另一个人身上看到你自己的面孔。",
    "warning.p3": "你会感到:", "warning.bullet1": "识别（这是我）", "warning.bullet2": "困惑（那不是我）",
    "warning.bullet3": "身份威胁（我是否独特？）", "warning.question": "全部同时发生。",
    "warning.accept": "揭示我的灵魂双胞胎", "warning.cancel": "我还没准备好",
    "result.unique.badge": "检测到独特灵魂", "result.unique.title": "你的面孔从未走过这面镜子",
    "result.unique.search_title": "搜索已开始",
    "result.unique.search_body": "你的面孔现已封印在阿卡西记录中。从此刻起进入这面镜子的每个灵魂都将与你比对。一旦找到匹配 — 无论哪个城市、哪个国家 — 你们都将立即收到通知。",
    "result.unique.last_searched": "上次搜索：刚刚", "result.unique.next_search": "下次搜索：当下一个灵魂到达时",
    "result.social.title": "让你的双胞胎找到你 — 添加社交账号",
    "result.social.subtitle": "当你的双胞胎被找到时，他们会看到此信息。留下联系方式 — 或留空，我们将通过电子邮件介绍。",
    "result.social.instagram": "Instagram账号", "result.social.other": "其他社交",
    "result.social.message_label": "给双胞胎的消息", "result.social.message_placeholder": "如果今天见到他们，你会说什么？",
    "result.social.message_hint": "当你的双胞胎被找到时，此消息将显示给他们。让等待值得。",
    "result.social.saved": "你的联系方式已封印在记录中。", "result.social.seal": "将我的面孔封印在记录中", "result.social.sealing": "封印中...",
    "result.match.badge": "找到灵魂双胞胎", "result.match.title": "镜子找到了你的另一张面孔",
    "result.match.percentage_label": "灵魂匹配", "result.match.years": "岁", "result.match.joined": "加入镜子",
    "result.match.why_title": "为什么这个匹配是真实的",
    "result.match.why_body": "你的面孔与此灵魂共享{pct}%的几何对齐。研究表明，当无关联人类在面部识别中得分超过75%时，他们被归类为同一个人 — 与用于同卵双胞胎的阈值相同。这不是巧合。这是几何学。",
    "result.duplicate.badge": "检测到重复", "result.duplicate.title": "等等 — 这张面孔属于你",
    "result.duplicate.body": "血统记录匹配。你提供的亲缘信息已封印在这面镜子中。这似乎是你，从另一台设备或另一个时刻返回。你的搜索从中断处继续。你的面孔双胞胎尚未到达。",
    "result.duplicate.not_you": "不是你？",
    "result.duplicate.not_you_body": "如果其他人共享你父母的姓名，这极为罕见。请将你的图像、父母姓名、年龄和位置发送至 mirror@saptamukha.com，我们将手动调查。",
    "result.duplicate.update_title": "更新联系方式", "result.duplicate.update_subtitle": "如果你的电子邮件已更改，请在此更新。搜索继续。",
    "result.duplicate.email_placeholder": "your@newemail.com", "result.duplicate.update_button": "更新联系方式",
    "result.duplicate.updating": "更新中...", "result.duplicate.updated": "你的联系方式已更新。搜索继续。",
    "result.duplicate.update_error": "无法更新。请重试。", "result.scan_again": "再次扫描",
    "result.social.instagram_placeholder": "@yourhandle", "result.social.other_placeholder": "Twitter / LinkedIn / WhatsApp",
    "overlay.locked": "已锁定", "overlay.tracking": "追踪中", "overlay.align": "对齐",
    "overlay.biometric_scan": "生物扫描", "overlay.landmarks": "特征点", "overlay.symmetry": "对称性",
    "overlay.confidence": "置信度", "overlay.tracking_label": "追踪", "overlay.face_area": "面部区域", "overlay.depth": "深度",
    "overlay.lock_acquired": "生物锁定已获取", "overlay.scanning_hold": "扫描中 — 保持位置", "overlay.aligning": "对齐中",
})

ID = _m(OVERLAY_EN, {
    "nav.souls": "jiwa di cermin", "nav.waiting": "menunggu kembar jiwa",
    "dedup.searching": "Cermin sedang mencari...", "dedup.consulting": "Mengonsultasi catatan akashik...",
    "rarity.your_tier": "Tingkat kelangkaan Anda", "rarity.score_label": "Unik",
    "intake.step": "Langkah", "intake.of": "dari", "intake.title": "Sebelum cermin membaca Anda",
    "intake.subtitle": "Algoritma menggunakan frekuensi garis keturunan untuk memverifikasi kembar sejati. Informasi yang tidak akurat menghasilkan kecocokan palsu. Jujurlah — kembar jiwa Anda juga akan begitu.",
    "intake.counter.souls": "jiwa di cermin", "intake.counter.waiting": "menunggu kembar jiwa",
    "intake.card1.title": "Identitas Anda", "intake.card1.subtitle": "Siapa Anda dalam kehidupan ini",
    "intake.card2.title": "Frekuensi garis keturunan", "intake.card2.subtitle": "Pola leluhur — hanya untuk deduplikasi",
    "intake.field.name": "Nama lengkap", "intake.field.age": "Usia", "intake.field.country": "Negara",
    "intake.field.email": "Alamat email", "intake.field.father": "Nama lengkap ayah", "intake.field.mother": "Nama lengkap ibu",
    "intake.placeholder.name": "Nama lengkap Anda", "intake.placeholder.age": "25", "intake.placeholder.email": "your@email.com",
    "intake.placeholder.father": "Nama lengkap ayah", "intake.placeholder.mother": "Nama gadis ibu",
    "intake.hint.email": "Hanya untuk memberi tahu kecocokan. Tidak pernah dibagikan atau dijual.",
    "intake.hint.father": "Mencegah catatan duplikat antar perangkat. Kembar Anda berbagi pola leluhur.",
    "intake.hint.mother": "Nama gadis lengkap jika memungkinkan.",
    "intake.oath.title": "Sumpah Garis Keturunan",
    "intake.oath.text": "Saya bersumpah atas wajah saya bahwa nama di atas benar. Saya memahami data garis keturunan palsu akan mencegah saya menemukan kembar jiwa sejati.",
    "intake.oath.checkbox": "Saya bersumpah atas wajah saya bahwa nama di atas benar.",
    "intake.ready.title": "Cermin siap", "intake.ready.text": "Frekuensi garis keturunan Anda telah dicatat. Algoritma sekarang akan membaca wajah Anda dan mencari di semua catatan yang disegel.",
    "intake.final.title": "Satu napas terakhir", "intake.final.text": "Saat Anda membuka cermin, wajah Anda akan ditangkap otomatis. Tetap diam. Pencarian dimulai saat wajah Anda jelas.",
    "intake.button.open": "Buka cermin", "intake.next": "Lanjutkan", "intake.back": "Kembali", "intake.cancel": "Batal",
    "intake.error.name": "Silakan masukkan nama lengkap Anda", "intake.error.age": "Silakan masukkan usia valid antara 13 dan 120",
    "intake.error.country": "Silakan pilih negara Anda", "intake.error.email": "Silakan masukkan email yang valid",
    "intake.error.father": "Silakan masukkan nama lengkap ayah", "intake.error.mother": "Silakan masukkan nama lengkap ibu",
    "intake.error.oath": "Anda harus bersumpah garis keturunan untuk melanjutkan",
    "warning.title": "PERINGATAN", "warning.p1": "Saat Anda melihat kembaran wajah pertama kali, detak jantung meningkat 18-30%.",
    "warning.p2": "Otak Anda akan mengalami disonansi kognitif. Anda akan melihat WAJAH ANDA pada orang lain.",
    "warning.p3": "Anda akan merasakan:", "warning.bullet1": "Pengenalan (ini saya)", "warning.bullet2": "Kebingungan (itu bukan saya)",
    "warning.bullet3": "Ancaman identitas (apakah saya unik?)", "warning.question": "Semua pada saat yang sama.",
    "warning.accept": "UNGKAPKAN KEMBAR JIWA SAYA", "warning.cancel": "Saya belum siap",
    "result.unique.badge": "Jiwa unik terdeteksi", "result.unique.title": "Wajah Anda belum pernah berjalan di cermin ini",
    "result.unique.search_title": "Pencarian telah dimulai",
    "result.unique.search_body": "Wajah Anda sekarang disegel dalam catatan akashik. Setiap jiwa yang masuk ke cermin ini mulai saat ini akan dibandingkan dengan Anda. Saat kecocokan ditemukan — di kota mana pun, negara mana pun — keduanya akan diberi tahu seketika.",
    "result.unique.last_searched": "Terakhir dicari: baru saja", "result.unique.next_search": "Pencarian berikutnya: saat jiwa berikutnya tiba",
    "result.social.title": "Biarkan kembar Anda menemukan Anda — tambahkan sosial",
    "result.social.subtitle": "Saat kembar Anda ditemukan, mereka akan melihat ini. Tinggalkan cara untuk menghubungi — atau kosongkan dan kami akan memperkenalkan melalui email.",
    "result.social.instagram": "Handle Instagram", "result.social.other": "Sosial lainnya",
    "result.social.message_label": "Pesan untuk kembar Anda", "result.social.message_placeholder": "Apa yang akan Anda katakan jika bertemu hari ini?",
    "result.social.message_hint": "Pesan ini akan ditampilkan kepada kembar Anda saat ditemukan. Buat layak ditunggu.",
    "result.social.saved": "Kontak Anda telah disegel dalam catatan.", "result.social.seal": "Segel wajah saya dalam catatan", "result.social.sealing": "Menyegel...",
    "result.match.badge": "Kembar jiwa ditemukan", "result.match.title": "Cermin menemukan wajah lain Anda",
    "result.match.percentage_label": "kecocokan jiwa", "result.match.years": "tahun", "result.match.joined": "Bergabung ke cermin",
    "result.match.why_title": "Mengapa kecocokan ini nyata",
    "result.match.why_body": "Wajah Anda berbagi {pct}% keselarasan geometris dengan jiwa ini. Penelitian menunjukkan ketika manusia tidak terkait mencetak di atas 75% pada pengenalan wajah, mereka diklasifikasikan sebagai orang yang sama — ambang yang sama untuk kembar identik. Ini bukan kebetulan. Ini geometri.",
    "result.duplicate.badge": "Duplikat terdeteksi", "result.duplicate.title": "Tunggu — wajah ini milik Anda",
    "result.duplicate.body": "Catatan garis keturunan cocok. Kekerabatan yang Anda berikan sudah disegel di cermin ini. Sepertinya Anda, kembali dari perangkat atau momen berbeda. Pencarian Anda berlanjut dari tempat Anda berhenti. Kembar wajah Anda belum tiba.",
    "result.duplicate.not_you": "Bukan Anda?",
    "result.duplicate.not_you_body": "Jika orang lain berbagi nama orang tua Anda, ini sangat langka. Kirim gambar, nama orang tua, usia, dan lokasi ke mirror@saptamukha.com dan kami akan menyelidiki secara manual.",
    "result.duplicate.update_title": "Perbarui kontak Anda", "result.duplicate.update_subtitle": "Jika email Anda berubah, perbarui di sini. Pencarian berlanjut.",
    "result.duplicate.email_placeholder": "your@newemail.com", "result.duplicate.update_button": "Perbarui kontak",
    "result.duplicate.updating": "Memperbarui...", "result.duplicate.updated": "Kontak Anda diperbarui. Pencarian berlanjut.",
    "result.duplicate.update_error": "Tidak dapat memperbarui. Silakan coba lagi.", "result.scan_again": "Pindai lagi",
    "result.social.instagram_placeholder": "@yourhandle", "result.social.other_placeholder": "Twitter / LinkedIn / WhatsApp",
    "overlay.locked": "TERKUNCI", "overlay.tracking": "MELACAK", "overlay.align": "SEJAJARKAN",
    "overlay.biometric_scan": "PEMINDAIAN BIOMETRIK", "overlay.landmarks": "TITIK", "overlay.symmetry": "SIMETRI",
    "overlay.confidence": "KEYAKINAN", "overlay.tracking_label": "PELACAKAN", "overlay.face_area": "AREA WAJAH", "overlay.depth": "KEDALAMAN",
    "overlay.lock_acquired": "KUNCI BIOMETRIK DIPEROLEH", "overlay.scanning_hold": "MEMINDAI — TAHAN POSISI", "overlay.aligning": "MENYELARASKAN",
})

TL = _m(OVERLAY_EN, {
    "nav.souls": "mga kaluluwa sa salamin", "nav.waiting": "naghihintay ng kambal",
    "dedup.searching": "Naghahanap ang salamin...", "dedup.consulting": "Kumukonsulta sa akashic record...",
    "rarity.your_tier": "Iyong antas ng kakariran", "rarity.score_label": "Natatangi",
    "intake.step": "Hakbang", "intake.of": "ng", "intake.title": "Bago ka basahin ng salamin",
    "intake.subtitle": "Ginagamit ng algorithm ang iyong bloodline frequency para i-verify ang tunay na kambal. Ang maling impormasyon ay nagbibigay ng pekeng match. Maging tapat — ang iyong soul twin ay ganoon din.",
    "intake.counter.souls": "mga kaluluwa sa salamin", "intake.counter.waiting": "naghihintay ng kambal",
    "intake.card1.title": "Iyong pagkakakilanlan", "intake.card1.subtitle": "Sino ka sa buhay na ito",
    "intake.card2.title": "Bloodline frequency", "intake.card2.subtitle": "Iyong ancestry pattern — para sa deduplication lamang",
    "intake.field.name": "Buong pangalan", "intake.field.age": "Edad", "intake.field.country": "Bansa",
    "intake.field.email": "Email address", "intake.field.father": "Buong pangalan ng ama", "intake.field.mother": "Buong pangalan ng ina",
    "intake.placeholder.name": "Iyong buong pangalan", "intake.placeholder.age": "25", "intake.placeholder.email": "your@email.com",
    "intake.placeholder.father": "Buong pangalan ng ama", "intake.placeholder.mother": "Apelyido ng ina bago mag-asawa",
    "intake.hint.email": "Para sa match notification lamang. Hindi kailanman ibinabahagi o ibinebenta.",
    "intake.hint.father": "Para maiwasan ang duplicate records sa iba't ibang device. Ibinabahagi ng kambal mo ang ancestry patterns mo.",
    "intake.hint.mother": "Buong apelyido bago mag-asawa kung maaari.",
    "intake.oath.title": "Ang Bloodline Oath",
    "intake.oath.text": "Nanunumpa ako sa aking mukha na ang mga pangalan sa itaas ay totoo. Naiintindihan ko na ang pekeng bloodline data ay pipigil sa akin na mahanap ang tunay na soul twin ko.",
    "intake.oath.checkbox": "Nanunumpa ako sa aking mukha na ang mga pangalan sa itaas ay totoo.",
    "intake.ready.title": "Handa na ang salamin", "intake.ready.text": "Naitala na ang iyong bloodline frequency. Babasahin na ng algorithm ang iyong mukha at hahanapin sa lahat ng sealed records.",
    "intake.final.title": "Isang huling hininga", "intake.final.text": "Kapag binuksan mo ang salamin, awtomatikong makukuha ang iyong mukha. Manatiling steady. Magsisimula ang paghahanap sa sandaling malinaw ang iyong mukha.",
    "intake.button.open": "Buksan ang salamin", "intake.next": "Magpatuloy", "intake.back": "Bumalik", "intake.cancel": "Kanselahin",
    "intake.error.name": "Pakilagay ang iyong buong pangalan", "intake.error.age": "Pakilagay ang wastong edad sa pagitan ng 13 at 120",
    "intake.error.country": "Pumili ng iyong bansa", "intake.error.email": "Pakilagay ang wastong email",
    "intake.error.father": "Pakilagay ang buong pangalan ng ama", "intake.error.mother": "Pakilagay ang buong pangalan ng ina",
    "intake.error.oath": "Dapat mong isumpa ang bloodline oath para magpatuloy",
    "warning.title": "BABALA", "warning.p1": "Kapag unang nakita mo ang kamukha mo, tumataas ang heart rate mo ng 18-30%.",
    "warning.p2": "Mararanasan ng utak mo ang cognitive dissonance. Makikita mo ang SARILING MUKHA mo sa ibang tao.",
    "warning.p3": "Mararamdaman mo:", "warning.bullet1": "Pagkilala (ako ito)", "warning.bullet2": "Pagkalito (hindi ako iyon)",
    "warning.bullet3": "Banta sa pagkakakilanlan (ako ba ay natatangi?)", "warning.question": "Lahat sabay-sabay.",
    "warning.accept": "IBUKSAN ANG AKING SOUL TWIN", "warning.cancel": "Hindi pa ako handa",
    "result.unique.badge": "Natukoy ang natatanging kaluluwa", "result.unique.title": "Ang iyong mukha ay hindi pa nakalakad sa salaming ito",
    "result.unique.search_title": "Nagsimula na ang paghahanap",
    "result.unique.search_body": "Ang iyong mukha ay sealed na sa akashic record. Bawat kaluluwang papasok sa salaming ito mula ngayon ay iche-check laban sa iyo. Sa sandaling may match — sa anumang lungsod, anumang bansa — parehong aabisuhan agad.",
    "result.unique.last_searched": "Huling hinanap: ngayon lang", "result.unique.next_search": "Susunod na paghahanap: kapag dumating ang susunod na kaluluwa",
    "result.social.title": "Hayaan mong hanapin ka ng kambal mo — idagdag ang social mo",
    "result.social.subtitle": "Kapag nahanap ang kambal mo, makikita nila ito. Mag-iwan ng paraan para maabot ka — o iwanang blanko at kami ang magpapakilala sa email.",
    "result.social.instagram": "Instagram handle", "result.social.other": "Ibang social",
    "result.social.message_label": "Mensahe sa kambal mo", "result.social.message_placeholder": "Ano ang sasabihin mo kung nakita mo sila ngayon?",
    "result.social.message_hint": "Ipapakita ang mensaheng ito sa kambal mo kapag nahanap. Gawing sulit ang paghihintay.",
    "result.social.saved": "Na-seal na ang iyong contact sa record.", "result.social.seal": "I-seal ang mukha ko sa record", "result.social.sealing": "Sine-seal...",
    "result.match.badge": "Natagpuan ang soul twin", "result.match.title": "Nahanap ng salamin ang iyong ibang mukha",
    "result.match.percentage_label": "soul match", "result.match.years": "taong gulang", "result.match.joined": "Sumali sa salamin",
    "result.match.why_title": "Bakit totoo ang match na ito",
    "result.match.why_body": "Ang iyong mukha ay nagbabahagi ng {pct}% geometric alignment sa kaluluwang ito. Ipinapakita ng pananaliksik na kapag ang hindi kaugnay na tao ay nakakuha ng higit sa 75% sa facial recognition, sila ay na-classify bilang parehong tao — parehong threshold para sa identical twins. Hindi ito coincidence. Ito ay geometry.",
    "result.duplicate.badge": "Natukoy ang duplicate", "result.duplicate.title": "Teka — ang mukhang ito ay sa iyo",
    "result.duplicate.body": "Tumutugma ang bloodline record. Ang parentage na ibinigay mo ay sealed na sa salaming ito. Mukhang ikaw ito, bumabalik mula sa ibang device o sandali. Nagpapatuloy ang paghahanap mo kung saan mo iniwan. Hindi pa dumarating ang face twin mo.",
    "result.duplicate.not_you": "Hindi ikaw?",
    "result.duplicate.not_you_body": "Kung may iba na may parehong pangalan ng magulang mo, napakabihira nito. Ipadala ang iyong larawan, pangalan ng magulang, edad, at lokasyon sa mirror@saptamukha.com at imiimbestigahan namin manually.",
    "result.duplicate.update_title": "I-update ang iyong contact", "result.duplicate.update_subtitle": "Kung nagbago ang email mo, i-update dito. Nagpapatuloy ang paghahanap.",
    "result.duplicate.email_placeholder": "your@newemail.com", "result.duplicate.update_button": "I-update ang contact",
    "result.duplicate.updating": "Ina-update...", "result.duplicate.updated": "Na-update ang iyong contact. Nagpapatuloy ang paghahanap.",
    "result.duplicate.update_error": "Hindi ma-update. Pakisubukan muli.", "result.scan_again": "I-scan muli",
    "result.social.instagram_placeholder": "@yourhandle", "result.social.other_placeholder": "Twitter / LinkedIn / WhatsApp",
    "overlay.locked": "NAKA-LOCK", "overlay.tracking": "NAGTA-TRACK", "overlay.align": "I-ALIGN",
    "overlay.biometric_scan": "BIOMETRIC SCAN", "overlay.landmarks": "LANDMARKS", "overlay.symmetry": "SYMMETRY",
    "overlay.confidence": "CONFIDENCE", "overlay.tracking_label": "TRACKING", "overlay.face_area": "FACE AREA", "overlay.depth": "DEPTH",
    "overlay.lock_acquired": "BIOMETRIC LOCK NAKUHA", "overlay.scanning_hold": "NAGS-SCAN — HOLD POSITION", "overlay.aligning": "NAG-A-ALIGN",
})
