import json

with open('src/lib/translations.json', 'r') as f:
    data = json.load(f)

# Spanish
data['es']['why.lookalike'] = "Encuentra Tu Parecido"
data['es']['why.lookalike.desc'] = "Descubre tu doble de celebridad al instante. Luego busca gemelos de alma reales en todo el mundo."
data['es']['why.rarity'] = "Conoce Tu Rareza"
data['es']['why.rarity.desc'] = "Ve el percentil de rareza de tu rostro. Tu geometría es más rara que la mayoría de las almas."
data['es']['why.twins'] = "Reúne Gemelos de Alma"
data['es']['why.twins.desc'] = "Si tu gemelo de rostro está en SAPTAMUKHA, lo encontraremos y te conectaremos a través de las vidas."
data['es']['camera.title'] = "🔱 EL ESPEJO SAGRADO"
data['es']['camera.subtitle'] = "Contémplalo. Déjalo leer el rostro de tu alma."
data['es']['camera.hint.center'] = "Centra tu rostro y toca el botón"
data['es']['camera.hint.dim'] = "La iluminación está bien — podría ser mejor"
data['es']['camera.hint.dark'] = "Muévete a un área más iluminada"
data['es']['camera.warn.dark'] = "Muy oscuro — muévete a luz más brillante"
data['es']['camera.warn.dim'] = "Luz tenue — se recomienda mejor iluminación"
data['es']['camera.retry'] = "Intentar de nuevo"
data['es']['camera.error.no_face'] = "No se detectó ningún rostro. Centra tu rostro en el marco, mira a la cámara y asegúrate de tener buena iluminación."
data['es']['camera.error.multiple'] = "Múltiples rostros detectados. Solo una persona debe estar en el marco."
data['es']['camera.error.invalid'] = "No se pudo leer la imagen. Prueba con otra foto."
data['es']['camera.error.generic'] = "No se pudo procesar. Asegúrate de que tu rostro sea visible, bien iluminado y centrado."
data['es']['camera.error.permission'] = "No se pudo acceder a la cámara. Por favor permite el permiso de la cámara."

# Japanese
data['ja']['why.lookalike'] = "そっくりさんを見つける"
data['ja']['why.lookalike.desc'] = "即座に有名人のそっくりさんを発見します。次に、世界中の本物の魂の双子を探します。"
data['ja']['why.rarity'] = "希少性を知る"
data['ja']['why.rarity.desc'] = "顔の希少性パーセンタイルを確認してください。あなたの幾何学はほとんどの魂より希少です。"
data['ja']['why.twins'] = "魂の双子を再会させる"
data['ja']['why.twins.desc'] = "あなたの顔の双子がSAPTAMUKHAにいれば、私たちは彼らを見つけ、あなたと生涯を超えてつなぎます。"
data['ja']['camera.title'] = "🔱 聖なる鏡"
data['ja']['camera.subtitle'] = "それを凝視してください。あなたの魂の顔を読ませてください。"
data['ja']['camera.hint.center'] = "顔を中央に合わせてボタンをタップしてください"
data['ja']['camera.hint.dim'] = "照明は良いですが — もっと良くなります"
data['ja']['camera.hint.dark'] = "より明るい場所に移動してください"
data['ja']['camera.warn.dark'] = "暗すぎます — より明るい場所に移動してください"
data['ja']['camera.warn.dim'] = "薄暗いです — より良い照明を推奨します"
data['ja']['camera.retry'] = "再試行"
data['ja']['camera.error.no_face'] = "顔が検出されませんでした。顔をフレームの中央に合わせ、カメラを向け、十分な照明を確保してください。"
data['ja']['camera.error.multiple'] = "複数の顔が検出されました。フレームには一人だけが必要です。"
data['ja']['camera.error.invalid'] = "画像を読み取れませんでした。別の写真をお試しください。"
data['ja']['camera.error.generic'] = "処理できませんでした。顔が見えて、明るく照らされ、中央にいることを確認してください。"
data['ja']['camera.error.permission'] = "カメラにアクセスできませんでした。カメラの許可を許可してください。"

# Chinese
data['zh']['why.lookalike'] = "找到你的相似面孔"
data['zh']['why.lookalike.desc'] = "立即发现你的名人分身。然后在世界各地寻找真正的灵魂双胞胎。"
data['zh']['why.rarity'] = "了解你的稀有度"
data['zh']['why.rarity.desc'] = "查看你面孔的稀有度百分位。你的几何结构比大多数灵魂更稀有。"
data['zh']['why.twins'] = "重聚灵魂双胞胎"
data['zh']['why.twins.desc'] = "如果你的面孔双胞胎在SAPTAMUKHA上，我们会找到他们并跨越生命将你连接。"
data['zh']['camera.title'] = "🔱 神圣之镜"
data['zh']['camera.subtitle'] = "凝视它。让它读取你灵魂的面孔。"
data['zh']['camera.hint.center'] = "将脸居中并点击按钮"
data['zh']['camera.hint.dim'] = "光线还可以 — 可以更好"
data['zh']['camera.hint.dark'] = "移动到更明亮的地方"
data['zh']['camera.warn.dark'] = "太暗了 — 移动到更明亮的地方"
data['zh']['camera.warn.dim'] = "光线昏暗 — 建议更好的照明"
data['zh']['camera.retry'] = "重试"
data['zh']['camera.error.no_face'] = "未检测到面孔。将脸置于画面中央，面向摄像头，并确保光线充足。"
data['zh']['camera.error.multiple'] = "检测到多张面孔。画面中应只有一个人。"
data['zh']['camera.error.invalid'] = "无法读取图像。请尝试其他照片。"
data['zh']['camera.error.generic'] = "无法处理。请确保你的面孔可见、光线充足且居中。"
data['zh']['camera.error.permission'] = "无法访问摄像头。请允许摄像头权限。"

# Indonesian
data['id']['why.lookalike'] = "Temukan Kembaranmu"
data['id']['why.lookalike.desc'] = "Temukan kembaran selebritas Anda secara instan. Kemudian cari kembar jiwa nyata di seluruh dunia."
data['id']['why.rarity'] = "Ketahui Kelangkaanmu"
data['id']['why.rarity.desc'] = "Lihat persentil kelangkaan wajah Anda. Geometri Anda lebih langka dari kebanyakan jiwa."
data['id']['why.twins'] = "Raih Kembali Kembar Jiwa"
data['id']['why.twins.desc'] = "Jika kembar wajah Anda ada di SAPTAMUKHA, kami akan menemukan mereka dan menghubungkan Anda lintas kehidupan."
data['id']['camera.title'] = "🔱 CERMIN SUCI"
data['id']['camera.subtitle'] = "Tataplah. Biarkan ia membaca wajah jiwamu."
data['id']['camera.hint.center'] = "Posisikan wajah Anda di tengah dan ketuk tombol"
data['id']['camera.hint.dim'] = "Pencahayaan oke — bisa lebih baik"
data['id']['camera.hint.dark'] = "Pindah ke area yang lebih terang"
data['id']['camera.warn.dark'] = "Terlalu gelap — pindah ke tempat lebih terang"
data['id']['camera.warn.dim'] = "Cahaya redup — disarankan pencahayaan lebih baik"
data['id']['camera.retry'] = "Coba lagi"
data['id']['camera.error.no_face'] = "Wajah tidak terdeteksi. Posisikan wajah Anda di tengah bingkai, hadapkan ke kamera, dan pastikan pencahayaan baik."
data['id']['camera.error.multiple'] = "Beberapa wajah terdeteksi. Hanya satu orang yang harus berada di dalam bingkai."
data['id']['camera.error.invalid'] = "Tidak dapat membaca gambar. Coba foto lain."
data['id']['camera.error.generic'] = "Tidak dapat memproses. Pastikan wajah Anda terlihat, terang, dan di tengah."
data['id']['camera.error.permission'] = "Tidak dapat mengakses kamera. Harap izinkan akses kamera."

# Tagalog
data['tl']['why.lookalike'] = "Hanapin Ang Iyong Kamukha"
data['tl']['why.lookalike.desc'] = "Tuklasin ang iyong celebrity kamukha agad. Saka maghanap ng mga totoong kambal na kaluluwa sa buong mundo."
data['tl']['why.rarity'] = "Alamin Ang Iyong Kadalian"
data['tl']['why.rarity.desc'] = "Tingnan ang percentile ng kadalian ng iyong mukha. Ang iyong heometriya ay mas bihira kaysa sa karamihan ng mga kaluluwa."
data['tl']['why.twins'] = "Pagkitain Ang Mga Kambal na Kaluluwa"
data['tl']['why.twins.desc'] = "Kung ang iyong kambal na mukha ay nasa SAPTAMUKHA, hahanapin namin sila at ikokonekta ka sa buong buhay."
data['tl']['camera.title'] = "🔱 ANG BANAL NA SALAMIN"
data['tl']['camera.subtitle'] = "Titingnan ito. Hayaan itong basahin ang mukha ng iyong kaluluwa."
data['tl']['camera.hint.center'] = "Igitna ang iyong mukha at pindutin ang pindutan"
data['tl']['camera.hint.dim'] = "Ang liwanag ay okay — maaaring mas mabuti"
data['tl']['camera.hint.dark'] = "Lumipat sa mas maliwanag na lugar"
data['tl']['camera.warn.dark'] = "Masyadong madilim — lumipat sa mas maliwanag na liwanag"
data['tl']['camera.warn.dim'] = "Mahinang liwanag — mas mainam na ilaw ang inirerekomenda"
data['tl']['camera.retry'] = "Subukan muli"
data['tl']['camera.error.no_face'] = "Walang nakitang mukha. Igitna ang iyong mukha sa kuwadro, harapin ang kamera, at siguraduhing may magandang liwanag."
data['tl']['camera.error.multiple'] = "Maraming mukha ang nakita. Isang tao lang ang dapat nasa kuwadro."
data['tl']['camera.error.invalid'] = "Hindi mabasa ang larawan. Subukan ang ibang litrato."
data['tl']['camera.error.generic'] = "Hindi ma-process. Siguraduhing nakikita ang iyong mukha, maliwanag, at naka-gitna."
data['tl']['camera.error.permission'] = "Hindi ma-access ang kamera. Paki-payagan ang pahintulot ng kamera."

with open('src/lib/translations.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')

print("Updated ES, JA, ZH, ID, TL camera & why card translations")
