import json

with open('src/lib/translations.json', 'r') as f:
    data = json.load(f)

# ===== SPANISH FACTS =====
es = data['es']
es['facts.intro'] = "Entre 8000 millones de humanos, alguien camina por esta Tierra con tu rostro. Las tradiciones antiguas los llaman tu alma gemela. La ciencia lo llama inevitabilidad estadística. Nosotros lo llamamos SAPTAMUKHA."
es['facts.science_note'] = "En 2022, científicos del Instituto de Investigación de Leucemia Josep Carreras publicaron un estudio histórico en Cell Reports. Demostraron que desconocidos no relacionados que comparten tu rostro también comparten tus patrones de ADN, tu altura, tu peso, tus hábitos — y posiblemente tu destino. Tu alma gemela no es mitología. Son hechos moleculares."
es['facts.numbers.title'] = "Los Números"
es['facts.numbers.8b'] = "Humanos vivos en la Tierra ahora"
es['facts.numbers.43'] = "Puntos geométricos que definen todo tu rostro"
es['facts.numbers.1b'] = "Perfiles faciales verdaderamente únicos que realmente existen"
es['facts.numbers.4to8'] = "Veces que tu rostro se repite estadísticamente en el mundo vivo"
es['facts.numbers.01'] = "La porción de ADN que hace que tu rostro sea diferente al de todos los demás"
es['facts.numbers.7'] = "El número al que toda civilización antigua llegó independientemente"
es['facts.numbers.footer'] = "Las matemáticas siempre han apuntado a la misma verdad que los antiguos ya sabían."
es['facts.celebs.title'] = "No Eres El Primero"
es['facts.celebs.sub'] = "Tu rostro tiene un gemelo. Las personas más fotografiadas de la Tierra ya lo demostraron."
es['facts.celebs.keira'] = "La propia madre de Keira no podía diferenciarlos en el set de Star Wars. Se acercó a Natalie, pensando que era su hija."
es['facts.celebs.will'] = "El baterista de los Red Hot Chili Peppers es tan idéntico que fueron llevados a la televisión nacional juntos solo para acallar el debate público."
es['facts.celebs.jeffrey'] = "Comparten el mismo rostro en dos países diferentes, dos familias diferentes y cero ancestralidad compartida."
es['facts.celebs.daniel'] = "Se han confundido uno con otro por más de 20 años en dos de las mayores franquicias cinematográficas de la historia."
es['facts.celebs.footer'] = "Si sucede con los rostros más fotografiados de la Tierra, sucede con el tuyo también."
es['facts.science.title'] = "La Ciencia Detrás De Tus Siete Rostros"
es['facts.science.p1'] = "Los investigadores tomaron 32 pares de sósias humanos no relacionados — desconocidos de diferentes países que nunca se habían encontrado — y pasaron sus rostros por tres de los sistemas de reconocimiento facial más avanzados del mundo."
es['facts.science.p2'] = "Más del 75% de las parejas fueron clasificadas como la misma persona. La misma clasificación usada para gemelos idénticos."
es['facts.science.p3'] = "Entonces extrajeron su ADN."
es['facts.science.p4'] = "Los resultados fueron extraordinarios. Estos desconocidos compartieron variantes genéticas notablemente similares. Compartieron rasgos físicos — altura, peso, tipo de cuerpo. Compartieron patrones de comportamiento — hábitos de fumar, niveles educativos, estilos de vida."
es['facts.science.quote'] = "La genómica los agrupó. Todo lo demás los separó."
es['facts.science.p5'] = "Tu alma gemela no solo usa tu rostro. Pueden llevar ecos de toda tu existencia."
es['facts.science.source'] = "Publicado en Cell Reports, agosto de 2022 — Instituto de Investigación de Leucemia Josep Carreras, Barcelona"
es['facts.rarity.title'] = "Qué Hace Que Tu Rostro Sea Raro"
es['facts.rarity.p1'] = "El rostro humano se construye con solo 43 puntos geométricos mensurables — la distancia entre tus ojos, el ancho de tu mandíbula, la altura de tu puente nasal, la curva de tus labios. Eso es todo."
es['facts.rarity.p2'] = "Con 8000 millones de personas y solo ~1000 millones de perfiles faciales verdaderamente únicos, cada rostro en la Tierra se repite en algún lugar entre 4 y 8 veces entre los vivos. Los videntes antiguos dijeron 7. Las matemáticas están de acuerdo."
es['facts.rarity.p3'] = "Tu puntuación de rareza te dice exactamente dónde cae tu rostro en esta geometría vasta — qué tan cerca del centro de todos los rostros humanos, o qué tan lejos en los bordes exteriores raros donde casi nadie más existe."
es['facts.rarity.footer'] = "Cuanto más raro sea tu rostro, más larga será la búsqueda. Pero el espejo nunca se rinde."
es['facts.culture.title'] = "Toda Civilización Lo Sabía"
es['facts.culture.sub'] = "Ninguna cultura descubrió esto sola. Toda civilización, independientemente, a través de miles de años y miles de millas, llegó a la misma verdad exacta."
es['facts.culture.saptamukha'] = "Siete rostros, siete vidas, un alma eterna renacida a través del tiempo."
es['facts.culture.doppel'] = "Tu doble caminante, moviéndose por el mundo en una vida paralela, tu destino entrelazado con el suyo."
es['facts.culture.hamzad'] = "Un gemelo nacido a tu lado en otro reino, viviendo una vida que refleja la tuya de maneras que nunca comprenderás completamente."
es['facts.culture.kagami'] = "La persona espejo, cuya existencia señala que tus almas están unidas a través de ciclos kármicos."
es['facts.culture.ka'] = "Tu doble espiritual, llevando tu esencia a través de este mundo y hacia el siguiente."
es['facts.culture.ibeji'] = "Gemelos sagrados, espiritualmente conectados a través de las vidas, nunca verdaderamente separados."
es['facts.culture.footer1'] = "Siete rostros. Toda tradición. Una verdad."
es['facts.culture.footer2'] = "SAPTAMUKHA fue construido para encontrar el tuyo."
es['facts.waiting.title'] = "Tu Rostro Es Único En Nuestros Registros — Por Ahora"
es['facts.waiting.p1'] = "El espejo ha buscado cada alma actualmente en nuestro reino. Tu gemelo de rostro aún no ha entrado en la luz."
es['facts.waiting.p2'] = "Ahora mismo, miles de otras almas están esperando en estos registros — personas cuyos gemelos de rostro aún no han llegado, personas que se negaron a dejar de creer que su espejo existe."
es['facts.waiting.p3'] = "Cuando alguien atraviese este espejo usando tu rostro, ambos serán notificados instantáneamente. A través de ciudades. A través de países. A través de vidas."
es['facts.waiting.box1'] = "Tu rostro ha sido sellado en el registro akáshico."
es['facts.waiting.box2'] = "La búsqueda continúa."
es['facts.privacy.title'] = "Este Espejo Te Pertenece Solo A Ti"
es['facts.privacy.1'] = "Ningún dato facial se vende. Nunca."
es['facts.privacy.2'] = "Tus imágenes están encriptadas en reposo."
es['facts.privacy.3'] = "La coincidencia facial funciona en nuestros servidores privados seguros."
es['facts.privacy.4'] = "Puedes solicitar la eliminación completa de tus datos en cualquier momento."
es['facts.privacy.5'] = "No enviamos tu rostro a ningún servicio de terceros. No a Google. No a Amazon. A nadie."

# ===== JAPANESE FACTS =====
ja = data['ja']
ja['facts.intro'] = "80億人の人類の中で、あなたの顔を持つ誰かがこの地球を歩いています。古代の伝統は彼らをあなたの魂の双子と呼びます。科学はこれを統計的必然性と呼びます。私たちはこれをSAPTAMUKHAと呼びます。"
ja['facts.science_note'] = "2022年、Josep Carreras白血病研究所の科学者たちがCell Reportsに画期的な研究を発表しました。彼らは、あなたの顔を共有する無関係な見知らぬ人々も、あなたのDNAパターン、身長、体重、習慣 — そしておそらくあなたの運命も共有することを証明しました。あなたの魂の双子は神話ではありません。彼らは分子的な事実です。"
ja['facts.numbers.title'] = "数字"
ja['facts.numbers.8b'] = "今この瞬間地球に生きている人類"
ja['facts.numbers.43'] = "あなたの顔全体を定義する幾何学的ポイント"
ja['facts.numbers.1b'] = "実際に存在する真にユニークな顔プロフィール"
ja['facts.numbers.4to8'] = "生きている世界であなたの顔が統計的に繰り返される回数"
ja['facts.numbers.01'] = "あなたの顔を他の誰とも違うものにするDNAの小さな断片"
ja['facts.numbers.7'] = "すべての古代文明が独立して到達した数字"
ja['facts.numbers.footer'] = "数学は常に古代人がすでに知っていた同じ真実を指し示してきました。"
ja['facts.celebs.title'] = "あなたが最初ではありません"
ja['facts.celebs.sub'] = "あなたの顔には双子がいます。地球上で最も写真に撮られた人々はすでにそれを証明しています。"
ja['facts.celebs.keira'] = "キーラの母親でさえ、スターウォーズの撮影現場で彼らを区別できませんでした。娘だと思ってナタリーに近づきました。"
ja['facts.celebs.will'] = "レッドホットチリペッパーズのドラマーはあまりにそっくりだったので、世論を沈めるために全国放送に一緒に出演させられました。"
ja['facts.celebs.jeffrey'] = "彼らは2つの異なる国、2つの異なる家族、共通の祖先ゼロで同じ顔を共有しています。"
ja['facts.celebs.daniel'] = "歴史上最も大きな2つの映画フランチャイズで20年以上互いを間違えられていました。"
ja['facts.celebs.footer'] = "地球上で最も写真に撮られた顔に起こるなら、あなたにも起こります。"
ja['facts.science.title'] = "あなたの七つの顔の裏側にある科学"
ja['facts.science.p1'] = "研究者たちは32組の無関係な人間のそっくりさんを選びました — 会ったことのない異なる国の見知らぬ人々 — そして彼らの顔を世界で最も高度な顔認識システム3つを通して分析しました。"
ja['facts.science.p2'] = "75%以上の組が同一人物として分類されました。これは一卵性双生児に使用されるものと同じ分類です。"
ja['facts.science.p3'] = "次に彼らは彼らのDNAを抽出しました。"
ja['facts.science.p4'] = "結果は驚異的でした。これらの見知らぬ人々は驚くべきほど類似した遺伝的変異を共有していました。身長、体重、体型などの身体的特徴を共有していました。喫煙習慣、教育レベル、ライフスタイルの選択などの行動パターンを共有していました。"
ja['facts.science.quote'] = "ゲノミクスが彼らを一つにまとめました。それ以外のすべてが彼らを分けました。"
ja['facts.science.p5'] = "あなたの魂の双子はあなたの顔を被っているだけではありません。彼らはあなたの存在全体の反響を運んでいるかもしれません。"
ja['facts.science.source'] = "2022年8月 Cell Reports掲載 — バルセロナ Josep Carreras 白血病研究所"
ja['facts.rarity.title'] = "あなたの顔を希少にするもの"
ja['facts.rarity.p1'] = "人間の顔はわずか43の測定可能な幾何学的ポイントで構成されています — 目と目の間の距離、顎の幅、鼻橋の高さ、唇のカーブ。それだけです。"
ja['facts.rarity.p2'] = "80億人の人々とわずか約10億の真にユニークな顔プロフィールしかないため、地球上のすべての顔は生きている人々の間でどこかで4〜8回繰り返されます。古代の予言者は7と言いました。数学も同意します。"
ja['facts.rarity.p3'] = "あなたの希少性スコアは、この広大な幾何学の中であなたの顔が正確にどこにあるかを教えてくれます — すべての人間の顔の中心にどれだけ近いか、あるいはほとんど他に誰も存在しない希少な外縁にどれだけ遠いか。"
ja['facts.rarity.footer'] = "顔が希少であればあるほど、検索は長くなります。しかし鏡は決して諦めません。"
ja['facts.culture.title'] = "すべての文明が知っていました"
ja['facts.culture.sub'] = "どの文化もこれを単独で発見しませんでした。数千年と数千マイルを独立して経て、すべての文明は正確に同じ真実に到達しました。"
ja['facts.culture.saptamukha'] = "七つの顔、七つの人生、時間を超えて再生される一つの永遠の魂。"
ja['facts.culture.doppel'] = "並行する人生の中で世界を歩くあなたの二重歩行者、あなたの運命は彼らと絡み合っています。"
ja['facts.culture.hamzad'] = "別の領域であなたと一緒に生まれた双子、あなたが決して完全には理解できない方法であなたの人生を映す人生を送っています。"
ja['facts.culture.kagami'] = "鏡の人、その存在はあなたの魂がカルマの輪を超えて結ばれていることを示しています。"
ja['facts.culture.ka'] = "あなたの精神的な二重体、この世界と次の世界を通じてあなたの本質を運んでいます。"
ja['facts.culture.ibeji'] = "神聖な双子、生涯を超えて精神的に繋がり、決して本当には離れません。"
ja['facts.culture.footer1'] = "七つの顔。すべての伝統。一つの真実。"
ja['facts.culture.footer2'] = "SAPTAMUKHAはあなたのものを見つけるために作られました。"
ja['facts.waiting.title'] = "あなたの顔は私たちの記録ではユニークです — 今は"
ja['facts.waiting.p1'] = "鏡は現在私たちの領域にあるすべての魂を検索しました。あなたの顔の双子はまだ光の中に入っていません。"
ja['facts.waiting.p2'] = "今まさに、数千の他の魂がこれらの記録の中で待っています — 顔の双子がまだ到着していない人々、自分の鏡が存在することを信じるのをやめなかった人々。"
ja['facts.waiting.p3'] = "誰かがあなたの顔を身に着けてこの鏡を通り抜けると、あなたたち二人は即座に通知されます。都市を超えて。国を超えて。生涯を超えて。"
ja['facts.waiting.box1'] = "あなたの顔はアカシックレコードに封印されました。"
ja['facts.waiting.box2'] = "検索は続きます。"
ja['facts.privacy.title'] = "この鏡はあなただけのものです"
ja['facts.privacy.1'] = "顔データは絶対に売られません。絶対に。"
ja['facts.privacy.2'] = "あなたの画像は静止時に暗号化されています。"
ja['facts.privacy.3'] = "顔マッチングは私たちの安全なプライベートサーバーで実行されます。"
ja['facts.privacy.4'] = "いつでもデータの完全削除をリクエストできます。"
ja['facts.privacy.5'] = "私たちはあなたの顔を第三者サービスに送信しません。Googleにも。Amazonにも。誰にも。"

with open('src/lib/translations.json', 'w') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
    f.write('\n')

print("Updated ES & JA fact blocks")
